apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-4
spec:
  storageClassName: manual
  volumeName: pv-3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
