---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: default
spec:
  hard:
    pods: "8"
    requests.cpu: "2"
    requests.memory: 3Gi
    limits.cpu: "3"
    limits.memory: 6Gi
